Areas/Admin/Controllers/quanLyNhomQuyenController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Text.Json;
using WEBSITE_TRAVELBOOKING.Core;
using WEBSITE_TRAVELBOOKING.Helper;
using WEBSITE_TRAVELBOOKING.Infrastructure;
using WEBSITE_TRAVELBOOKING.Models;
using X.PagedList;

namespace WEBSITE_TRAVELBOOKING.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Auth]
    public class quanLyNhomQuyenController : Controller
    {
        public IUnitOfWork _unitOfWork;
        private IWebHostEnvironment Environment;
        private SysUser getAccout;

        public quanLyNhomQuyenController(IUnitOfWork unitOfWork, IWebHostEnvironment _environment)
        {
            _unitOfWork = unitOfWork;
            Environment = _environment;
        }

        public IActionResult Index()
        {
            //ViewBag.NhomQuyen = _unitOfWork.Repository<SysRole>().GetAll(filter: h => h.Status == true).ToList();
            return View();
        }

        public IActionResult childIndex(int? page, string searchValue)
        {
            var getAccout = Account.GetAccount();
            if (getAccout.IdRole == 1)
            {
                //return View("_Menu");
                // hiển thị toàn bộ quyền                    
                var getRoleAll = _unitOfWork.Repository<SysRole>().GetAll(filter: (m => m.IdUserPrent == null)).ToList();
                if (!string.IsNullOrEmpty(searchValue))
                {
                    getRoleAll = getRoleAll.Where(m => m.Name.ToLower().Contains(searchValue.ToLower())).ToList();
                }
                #region Page
                page = page == null ? 1 : page;
                page = page < 1 ? 1 : page;
                var pageSizeAll = 10;
                var pageListViewAll = getRoleAll.ToPagedList(page ?? 1, pageSizeAll);
                #endregion
                #region ViewBag
                ViewBag.Partner = true;
                ViewBag.ListPartner = _unitOfWork.Repository<SysUser>().GetAll(m => m.IdRole == 3);
                #endregion
                return PartialView("childIndex", pageListViewAll);
            }
            // hiển thị quyền của partner
            var getRole = _unitOfWork.Repository<SysRole>().GetAll(filter: (m => m.IdUserPrent == getAccout.Id)).ToList();
            if (!string.IsNullOrEmpty(searchValue))
            {
                getRole = getRole.Where(m => m.Name.ToLower().Contains(searchValue.ToLower())).ToList();
            }
            #region Page
            page = page == null ? 1 : page;
            page = page < 1 ? 1 : page;
            var pageSize = 10;
            var pageListView = getRole.ToPagedList(page ?? 1, pageSize);
            #endregion
            #region ViewBag
            ViewBag.Partner = false;
            #endregion
            if (pageListView != null)
            {
                return PartialView("childIndex", pageListView);
            }
            return PartialView("childIndex");
        }

        public IActionResult themMoiNhomQuyen()
        {
            try
            {
                SysRole sysRole = new SysRole();
                return PartialView(sysRole);
            }
            catch (Exception)
            {

                throw;
            }
        }

        [HttpPost]
        public IActionResult themMoiNhomQuyen(SysRole sysRole)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    foreach (var modelStateKey in ModelState.Keys)
                    {
                        var modelStateVal = ModelState[modelStateKey];
                        foreach (var error in modelStateVal.Errors)
                        {
                            var key = modelStateKey;
                            var errorMessage = error.ErrorMessage;
                            ModelState.AddModelError(key, errorMessage);
                            return ValidationProblem(ModelState);
                        }
                    }
                }
                sysRole.Status = true;
                var getAccout = Account.GetAccount();
                if (getAccout.IdRole != 1)
                {
                    sysRole.IdUserPrent = Account.GetAccount()?.Id;
                }

                _unitOfWork.Repository<SysRole>().Insert(sysRole);

                return PartialView("Index");
            }
            catch (Exception ex)
            {
                throw;
            }
        }

        public IActionResult chinhSuaNhomQuyen(int id)
        {
            try
            {
                var sysRole = _unitOfWork.Repository<SysRole>().GetById(id);
                if (sysRole == null)
                {
                    return BadRequest();
                }
                return PartialView("chinhSuaNhomQuyen", sysRole);
            }
            catch (Exception)
            {

                throw;
            }
        }

        [HttpPost]
        public IActionResult chinhSuaNhomQuyen(SysRole sysRole)
        {
            try
            {
                var checksysRole = _unitOfWork.Repository<SysRole>().GetById(sysRole.Id);
                if (checksysRole == null)
                {
                    string key = "Name";
                    string errorMessage = "Tên nhóm quyền không được để trống!!";
                    ModelState.AddModelError(key, errorMessage);
                    return ValidationProblem(ModelState);
                }

                // Kiểm tra trường dữ liệu
                if (!ModelState.IsValid)
                {
                    foreach (var modelStateKey in ModelState.Keys)
                    {
                        var modelStateVal = ModelState[modelStateKey];
                        foreach (var error in modelStateVal.Errors)
                        {
                            var key = modelStateKey;
                            var errorMessage = error.ErrorMessage;
                            ModelState.AddModelError(key, errorMessage);
                            return ValidationProblem(ModelState);
                        }
                    }
                }
                checksysRole.Name = sysRole.Name;
                _unitOfWork.Repository<SysRole>().Update(checksysRole);

                TempData["SuccessMessage"] = "Chỉnh sửa thành công!";
                return PartialView("Index");

            }
            catch (Exception)
            {

                throw;
            }
        }

        public IActionResult chiTietNhomQuyen(int id)
        {
            try
            {
                var SysRoles = _unitOfWork.Repository<SysRole>().GetAll(filter: (m => m.Id == id), includeProperties: "SysUsers").FirstOrDefault();
                if (SysRoles == null) return PartialView("Index");
                return PartialView(SysRoles);
            }
            catch (Exception)
            {

                throw;
            }
        }

        public IActionResult xoaNhomQuyen(int id)
        {
            try
            {

                var getRole = _unitOfWork.Repository<SysRole>().GetById(id);
                if (getRole == null) return PartialView("Index");
                _unitOfWork.Repository<SysRole>().Delete(getRole);
                TempData["SuccessMessage"] = "Xóa thành công!";
                //return PartialView("childIndex");
                return Json(new { result = true, message = "Xóa thành công!" });

            }
            catch (Exception)
            {
                return Json(new { result = false, message = "Lỗi khi xóa" });

            }
        }
        public IActionResult phanquyen(int id)
        {
            try
            {
                var getAccount = Account.GetAccount();
                if (getAccount == null)
                {
                    // lỗi chưa đăng nhâp
                }
                if (getAccount.IdRole == 1)// quyền admin
                {
                    var getRole = _unitOfWork.Repository<SysRole>().GetById(id);
                    if (getRole == null) return PartialView("Index");

                    var getRule = _unitOfWork.Repository<SysRule>().GetAll(filter: (m => m.IdRole == getRole.Id));
                    var getModule = _unitOfWork.Repository<SysModule>().GetAll(filter: (m => m.Status == true));

                    var mapRuleModule = (from module in getModule
                                         join rule in getRule
                                         on module.Id equals rule.IdModule into gj
                                         from subRule in gj.DefaultIfEmpty()
                                         select new ModelsAndRole()
                                         {
                                             Id = subRule?.Id ?? 0,
                                             IdModule = module.Id,
                                             IdRole = subRule?.IdRole ?? getRole.Id,
                                             Name = module.Name,
                                             NameController = module.NameController,
                                             PrentId = module.PrentId,
                                             Order= module.Order,
                                             IsView = subRule?.IsView ?? false,
                                             IsCreate = subRule?.IsCreate ?? false,
                                             IsEdit = subRule?.IsEdit ?? false,
                                             IsDelete = subRule?.IsDelete ?? false,
                                             IsPermission = subRule?.IsPermission ?? false
                                         }).ToList();
                    var tree = BuildRoleTree(mapRuleModule);

                    return PartialView(tree);
                }
                else
                {//quyền còn lại                
                    // Lấy quyền hiện tại của Partner (người đăng nhập)

Areas/Partner/Views/quanLyNhomQuyen/Index.cshtml
@using WEBSITE_TRAVELBOOKING.Models
@{
    Layout = "_AdminLayout";
    ViewData["TitleAdmin"] = "Quản lý nhóm quyền";
    var listRole = ViewBag.NhomQuyen as List<WEBSITE_TRAVELBOOKING.Models.SysRole>;
    var ruleAction = ViewData["RuleAll"] as ModelsAndRole;
}

<div class="container-fluid">
    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                @* <div class="page-title-right">
                <ol class="breadcrumb m-0">
                <li class="breadcrumb-item"><a href="javascript: void(0);">Hyper</a></li>
                <li class="breadcrumb-item"><a href="javascript: void(0);">Tables</a></li>
                <li class="breadcrumb-item active">Data Tables</li>
                </ol>
                </div> *@
                <h4 class="page-title">@ViewData["TitleAdmin"]</h4>
            </div>
        </div>
    </div>
    <!-- end page title -->

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div>
                        <div class="row formsearch">
                            @{
                                if (ruleAction != null && ruleAction.IsCreate == true)
                                {
                                    <div class="col-2">
                                        <a href="@Url.Action("themMoiNhomQuyen", "quanLyNhomQuyen")" class="btn btn-success mb-2" data-toggle='modal' data-sizeModal="abc">
                                            <i class="mdi mdi-plus-circle me-2"></i>Thêm mới
                                        </a>
                                    </div>
                                }
                            }
                            <div class="col-2">
                                <div class="dataTables_filter">
                                    <input type="search" class="form-control" id="" name="searchValue" placeholder="Tìm kiếm..." aria-controls="products-datatable">
                                </div>
                            </div>
                            <div class="col-2">
                                <button data-url="@Url.Action("childIndex", "quanLyNhomQuyen")" type="button" class="btn btn-info searchform">
                                    <i class="mdi mdi-magnify me-1"></i> <span>Tìm kiếm</span>
                                </button>
                            </div>
                        </div>
                        <div id="alertJs" class="mt-2"></div>
                        <div class="row py-2">
                            <div class="col-sm-12" id="DataTable">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/assets/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script>
    document.addEventListener("DOMContentLoaded", function () {
        $('#DataTable').load('/Admin/quanLyNhomQuyen/childIndex');
    });
    function SearchData() {
        var searchValue = $('#searchValue')[0].value;
        $.ajax({
            url: '/Admin/quanLyNhomQuyen/childIndex',
            type: 'GET',
            data: { searchValue: searchValue },
            success: function (data) {
                $("#DataTable").html(data);
            },
            error: function (xhr, status, error) {
                alert(xhr.responseText);
            }
        });
    }
</script>

Areas/Partner/Views/quanLyNhomQuyen/chiTietNhomQuyen.cshtml
@model WEBSITE_TRAVELBOOKING.Models.SysRole;
@{
    // Layout = "_AdminLayout";
    ViewData["TitleAdmin"] = "Chi tiết nhóm quyền";
    var getRole = ViewBag.getRole as WEBSITE_TRAVELBOOKING.Models.SysRole;
}

<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">@ViewData["TitleAdmin"]</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<div class="modal-body">
    <form id="dataForm" method="post" action="xoaNhomQuyen" novalidate>
        <input type="number" name="Id" value="@Model.Id" hidden />

        <div class="row">
            <div class="col-12">
                <div class="mb-3">
                    <label class="form-label" for="validationCustom01">Tên nhóm quyền</label>
                    <input type="text" class="form-control" name="Name" value="@Model.Name" readonly>
                    <div class="invalid-feedback"></div>
                </div>
            </div>
        </div>
    </form>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Đóng</button>
    @{
        if (Model.SysUsers.Count > 0)
        {
            <button type="button" class="btn bg-danger-subtle text-danger waves-effect text-start" onclick="alert('Không thể xóa nhóm quyền, Hiện tại có nhiều tài khoản đang dùng nhóm quyền này!!')">
                Xóa nhóm quyền
            </button>
        }
        else
        {
            <button type="button" data-toggle="ajax-modal" data-url="@Url.Action("xoaNhomQuyen", new { id = Model.Id })" class="btn bg-danger-subtle delete text-danger waves-effect text-start">
                Xóa nhóm quyền
            </button>
        }
    }
</div>
@* <div class="container-fluid">
    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <h4 class="page-title">@ViewData["TitleAdmin"]</h4>
            </div>
        </div>
    </div>
    <!-- end page title -->

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-5">
                            <div class="text-center d-block mb-4">
                                <img src="~/assets/images/users/avatar-2.jpg" class="img-fluid" />
                            </div>
                        </div>
                        <div class="col-lg-7">
                            <div class="ps-lg-4">
                                <h3 class="mt-0">Thông tin người dùng</h3>
                                <div class="mt-3">
                                    <p class="text-muted">
                                        <strong>Tên người dùng: </strong>
                                        @Model.Name
                                    </p>
                                    <p class="text-muted">
                                        <strong>Email: </strong>
                                        @Model.Email
                                    </p>
                                    <p class="text-muted">
                                        <strong>Địa chỉ: </strong>
                                        @Model.Local
                                    </p>
                                    <p class="text-muted">
                                        <strong>Tài khoản: </strong>
                                        @Model.Username
                                    </p>

                                    <p class="text-muted">
                                        <strong>Nhóm quyền: </strong>
                                        @getRole.Name
                                    </p>
                                    <p class="text-muted">
                                        <strong>Trạng thái: </strong>
                                        @(Model.Status == true ? "Kích hoạt" : "Chưa kích hoạt")
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <a class="btn btn-danger" href="@Url.Action("xoaTaiKhoan", "quanLyTaiKhoan", new {id = Model.Id})">Xóa</a>
                    <a href="@Url.Action("Index", "quanlyTaiKhoan")" class="btn btn-outline-secondary" type="submit">Quay lại</a>
                </div>
            </div>
        </div>
    </div>
</div> *@

Areas/Partner/Views/quanLyNhomQuyen/childIndex.cshtml
@model X.PagedList.IPagedList<WEBSITE_TRAVELBOOKING.Models.SysRole>
@using WEBSITE_TRAVELBOOKING.Helper;
@using WEBSITE_TRAVELBOOKING.Models
@using X.PagedList.Mvc.Core;
@using X.PagedList.Mvc.Core.Common
@using X.PagedList.Web.Common;
@{
    var ruleAction = ViewData["RuleAll"] as ModelsAndRole;
}

<div class="table-responsive">
    <table class="table table-sm table-centered w-100 dt-responsive nowrap">
        <thead class="table-light">
            <tr>
                <th class="text-center" width="170px">STT</th>
                <th>Nhóm quyền</th>
                @{
                    if (ruleAction != null && (ruleAction.IsEdit == true || ruleAction.IsDelete == true || ruleAction.IsPermission == true))
                    {
                        <th class="text-center" width="170px">Hàng động</th>
                    }
                }
            </tr>
        </thead>
        <tbody>
            @{
                int idx = 1;
            }
            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-center">@idx</td>
                    <td>@item.Name</td>
                    <td>
                        <div class="table-action">
                            @{
                                if (ruleAction != null && ruleAction.IsPermission == true)
                                {
                                    if (item.Id == 1)
                                    {
                                        <button class="btn btn-sm btn-info" title="Phân quyền" style="cursor:no-drop">
                                            <i class="mdi mdi-square-edit-outline"></i>
                                        </button>
                                    }
                                    else
                                    {
                                        <a href="@Url.Action("phanquyen", "quanLyNhomQuyen", new {id = item.Id})" class="btn btn-sm btn-info" title="Phân quyền" data-toggle='modal' data-sizeModal="modal-xl">
                                            <i class="mdi mdi-square-edit-outline"></i>
                                        </a>
                                    }
                                }
                                if (ruleAction != null && ruleAction.IsEdit == true)
                                {
                                    <a href="@Url.Action("chinhSuaNhomQuyen", "quanLyNhomQuyen", new {id = item.Id})" class="btn btn-sm btn-warning" title="Chỉnh sửa" data-toggle='modal' data-sizeModal="abc">
                                        <i class="mdi mdi-square-edit-outline"></i>
                                    </a>
                                }
                                if (ruleAction != null && ruleAction.IsDelete == true)
                                {
                                    if (item.Id == 1)
                                    {
                                        <button class="btn btn-sm btn-danger" title="Xóa" style="cursor:no-drop">
                                            <i class="mdi mdi-delete"></i>
                                        </button>
                                    }
                                    else
                                    {
                                        <a href="@Url.Action("chiTietNhomQuyen", "quanLyNhomQuyen", new {id = item.Id})" class="btn btn-sm btn-danger" title="Xóa" data-toggle='modal' data-sizeModal="abc">
                                            <i class="mdi mdi-delete"></i>
                                        </a>
                                    }
                                }
                            }
                        </div>
                    </td>
                </tr>
                idx++;
            }
        </tbody>
    </table>
    @{
        if (Model.Count > 0)
        {
            <div class="d-flex align-items-center justify-content-end py-1">
                @Html.PagedListPager(Model, page => Url.Action("childIndex", new { page }),
                     PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions() { HttpMethod = "GET", UpdateTargetId = "DataTable" }))
            </div>
        }
    }
</div>

Areas/Partner/Views/quanLyNhomQuyen/chinhSuaNhomQuyen.cshtml
@model WEBSITE_TRAVELBOOKING.Models.SysRole;
@{
    // Layout = "_AdminLayout";
    ViewData["TitleAdmin"] = "Chỉnh sửa nhóm quyền";
}


<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">@ViewData["TitleAdmin"]</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<div class="modal-body">
    <form id="dataForm" method="post" action="chinhSuaNhomQuyen" novalidate>
        <input type="number" name="Id" value="@Model.Id" hidden />
        <div class="row">
            <div class="col-12">
                <div class="mb-3">
                    <label class="form-label" for="validationCustom01">Tên nhóm quyền<span class="text-danger">*</span></label>
                    <input type="text" class="form-control" name="Name" placeholder="Tên đối tác" value="@Model.Name" required>
                    <div class="invalid-feedback"></div>
                </div>               
            </div>
        </div>
    </form>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Đóng</button>
    <button type="button" data-toggle="ajax-modal" data-url="@Url.Action("chinhSuaNhomQuyen")" class="btn bg-success-subtle edit text-success waves-effect text-start">
        Cập nhật
    </button>
</div>

Areas/Partner/Views/quanLyNhomQuyen/themMoiNhomQuyen.cshtml
@model WEBSITE_TRAVELBOOKING.Models.SysRole;
@{
    // Layout = "_AdminLayout";
    ViewData["TitleAdmin"] = "Thêm mới nhóm quyền";
}

<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">@ViewData["TitleAdmin"]</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<div class="modal-body">
    <form id="dataForm" method="post" action="themMoiNhomQuyen" novalidate>
        <div class="row">
            <div class="col-12">             
                <div class="mb-3">
                    <label class="form-label" for="validationCustom01">Tên nhóm quyền<span class="text-danger">*</span></label>
                    <input type="text" class="form-control" name="Name" placeholder="Tên nhóm quyền" required>
                    <div class="invalid-feedback"></div>
                </div>                       
            </div>            
        </div>
    </form>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Đóng</button>    
    <button type="button" data-toggle="ajax-modal" data-url="@Url.Action("themMoiNhomQuyen")" class="btn bg-success-subtle create text-success waves-effect text-start">
        Thêm mới
    </button>
</div>